/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [require("nativewind/preset")],
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#d5e3fc",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#d8e3fb",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#00dce5",
        "outline-variant": "#c3c6d6",
        "error": "#ba1a1a",
        "on-primary-container": "#ccd8ff",
        "on-secondary-fixed": "#0d1c2e",
        "inverse-primary": "#b2c5ff",
        "secondary-container": "#d5e3fc",
        "on-surface-variant": "#424654",
        "surface-variant": "#d8e3fb",
        "on-primary-fixed": "#001847",
        "on-surface": "#111c2d",
        "surface-bright": "#f9f9ff",
        "on-error": "#ffffff",
        "outline": "#737785",
        "on-secondary-container": "#57657a",
        "surface-container-low": "#f0f3ff",
        "secondary": "#515f74",
        "tertiary-container": "#00696e",
        "primary-fixed": "#dae2ff",
        "primary": "#0040a1",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#3a485b",
        "on-background": "#111c2d",
        "on-primary-fixed-variant": "#0040a1",
        "on-primary": "#ffffff",
        "surface-container-high": "#dee8ff",
        "surface-dim": "#cfdaf2",
        "on-tertiary-fixed": "#002021",
        "error-container": "#ffdad6",
        "background": "#f9f9ff",
        "tertiary-fixed": "#63f7ff",
        "on-tertiary-container": "#00eff9",
        "tertiary": "#004f53",
        "primary-fixed-dim": "#b2c5ff",
        "inverse-surface": "#263143",
        "inverse-on-surface": "#ecf1ff",
        "secondary-fixed-dim": "#b9c7df",
        "surface-tint": "#0056d2",
        "on-tertiary-fixed-variant": "#004f53",
        "primary-container": "#0056d2",
        "surface-container": "#e7eeff",
        "surface": "#f9f9ff",
        "surface-container-lowest": "#ffffff"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
